export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_MESSAGES_START = 'FETCH_MESSAGES_START';
export const FETCH_MESSAGES_SUCCEED = 'FETCH_MESSAGES_SUCCEED';
export const FETCH_MESSAGES_FAIL = 'FETCH_MESSAGES_FAIL';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_MESSAGE_START = 'ADD_MESSAGE_START';
export const ADD_MESSAGE_SUCCEED = 'ADD_MESSAGE_SUCCEED';
export const ADD_MESSAGE_FAIL = 'ADD_MESSAGE_FAIL';
